<a href="https://colab.research.google.com/github/osh9149/2026_DataScience/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A1%9C%EB%93%9C%EB%B0%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 파일 업로드

In [1]:
from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    print(f'업로드된 파일: {filename} ({len(uploaded[filename])} bytes)')

Saving seoul_temp.xls to seoul_temp.xls
업로드된 파일: seoul_temp.xls (225160 bytes)

#2. 폴더에서 읽어오기(/content)

##csv 파일의 경우

In [10]:
import pandas as pd

# 여기에 실제 CSV 파일 이름을 입력해주세요. (예: 'data.csv')
file_path = 'seoul_temp_c.csv'

try:
    df_local = pd.read_csv(file_path, encoding='cp949')
    print(f"'{file_path}' 파일을 성공적으로 불러왔습니다.")
    display(df_local.head())
except FileNotFoundError:
    print(f"오류: '{file_path}' 파일을 찾을 수 없습니다. 파일 이름을 확인하거나, 파일이 올바른 위치에 있는지 확인해주세요.")
except Exception as e:
    print(f"파일을 불러오는 중 오류가 발생했습니다: {e}")

'seoul_temp_c.csv' 파일을 성공적으로 불러왔습니다.

             날짜   지점  평균기온(℃)  최저기온(℃)  최고기온(℃)
0  \t2002-03-01  108      6.6      1.1     13.1
1  \t2002-03-02  108      7.0      4.5     11.5
2  \t2002-03-03  108      4.8      2.3      9.4
3  \t2002-03-04  108      4.2     -0.7      8.3
4  \t2002-03-05  108      4.0      1.4      6.2

##exel 파일의 경우(.xlsx)

In [7]:
import pandas as pd

# 여기에 실제 Excel 파일 이름을 입력해주세요. (예: 'my_excel_data.xlsx')
file_path = 'seoul_temp.xlsx'

try:
    df_local_excel = pd.read_excel(file_path)
    print(f"'{file_path}' 파일을 성공적으로 불러왔습니다.")
    display(df_local_excel.head())
except FileNotFoundError:
    print(f"오류: 로컬에 '{file_path}' 파일을 찾을 수 없습니다. 파일 이름을 확인하거나, 파일이 올바른 위치에 있는지 확인해주세요.")
except Exception as e:
    print(f"파일을 불러오는 중 오류가 발생했습니다: {e}")

'seoul_temp.xlsx' 파일을 성공적으로 불러왔습니다.

          날짜  평균기온(℃)  최저기온(℃)  최고기온(℃)
0 2002-03-01      6.6      1.1     13.1
1 2002-03-02      7.0      4.5     11.5
2 2002-03-03      4.8      2.3      9.4
3 2002-03-04      4.2     -0.7      8.3
4 2002-03-05      4.0      1.4      6.2

#3. 드라이브 마운트(구글 드라이브안에서 가져올 때)

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
import pandas as pd

# 구글 드라이브에 있는 엑셀 파일 경로를 지정해주세요.

file_path = '/content/drive/MyDrive/Colab Notebooks/seoul_temp.xlsx'
df = pd.read_excel(file_path)
print("엑셀 파일을 성공적으로 불러왔습니다.")
display(df.head())

엑셀 파일을 성공적으로 불러왔습니다.

          날짜  평균기온(℃)  최저기온(℃)  최고기온(℃)
0 2002-03-01      6.6      1.1     13.1
1 2002-03-02      7.0      4.5     11.5
2 2002-03-03      4.8      2.3      9.4
3 2002-03-04      4.2     -0.7      8.3
4 2002-03-05      4.0      1.4      6.2